config/routes.rb
Rainforest::Application.routes.draw do
  root 'products#homepage'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :products do
    resources :reviews
  end

end

app/models/product.rb
class Product < ActiveRecord::Base #Product.all
	validates :description, :name, :url,presence: true
	validates :price_in_cents, numericality: {only_integer: true} 

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%.2f",price_in_dollars)
	end

	has_many :reviews
	has_many :users, through: :reviews

end

app/models/review.rb
class Review < ActiveRecord::Base
	validates :comment, :presence => true
	belongs_to :user
	belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	

	has_many :reviews
	has_many :products, through: :reviews

	 has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
	 validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private 

  def current_user 
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  # it will make the method abilable to viewsw.

  def ensure_logged_in 
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path 
  	end
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


	def new
		@product = Product.new
	end

	def edit
		@product = Product.find(params[:id])
	end

	def create 
		@product = Product.new(product_params)

		if @product.save
			redirect_to products_url
		else
			render :new
		end
	end

	def update
		@product = Product.find(params[:id])

		if @product.update_attributes(product_params)
			redirect_to product_path(@product)
		else
			render :edit
		end
	end

	def destroy 
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end

	def show 
		@product = Product.find(params[:id])

		if current_user
			@review = @product.reviews.build
		end
	end


  	def index
    	@products = if params[:search]
      		Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    	else
      		Product.all
    	end

  		@products = @products.order('products.created_at ASC').page(params[:page])

    	respond_to do |format|
    		format.html
    		format.js
    	end
  	end



	private
	def product_params
		params.require(:product).permit(:name, :description, :url, :price_in_cents)
	end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :load_product
	before_filter :ensure_logged_in, only: [:create, :destroy]



	def index
		@reviews = Review.all
	end

	def show
		@review = Review.find(params[:id])
	end

	def create
		@review = @product.reviews.build(review_params)
		@review.user = current_user

		respond_to do |format|
			if @review.save 
				format.html { redirect_to product_path(@product.id), notice: 'Review added.'}
				format.js{} 
			else
				format.html { render 'product/show', alert: 'There was an error.'}
				format.js{}
			end
		end
	end

	def destroy
		@review = Review.find(params[:id])
		@review.destroy
	end

	def edit
		@review =  Review.find(params[:id])
	end

	def update
		@review = Review.find(params[:id])

		if @review.update_attributes(review_params)
			redirect_to product_path(@product) 
			# To defin the specific product 
		else
			render :edit
		end
	end

	private

	def review_params
		params.require(:review).permit(:comment, :product_id)
	end

	def load_product
		@product = Product.find(params[:product_id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_path, notice: "Logged in!"
    else
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_filter :ensure_logged_in, only: [:destroy, :edit,:index,:show,:update]

  def index
    @reviews = User.all
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new(user_params)
     if @user.save
        redirect_to products_url,notice:"Signed up!"
    else
        render "new"
    end
  end

  def show
      @user = User.find(params[:id])
  end
  
  def edit
      @user =  User.find(params[:id]) 
  end

  def update
      @user = User.find(params[:id])

    if @review.update_attributes(user_params)
        redirect_to product_path(@product) 
      # To defin the specific product 
    else
       render :edit
    end
  end

 def destroy
       @user = User.find(params[:id])
       @user.destroy
  end


  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name,:user_id,:picture)
  end

# ここでのパーミッションにIDを含めず何度も死んでいる。
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Rainforest</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<h1 id="title">Products</h1>
	<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert] %>
	<p id="alert"><%= flash[:alert] %></p>
	<% end %>

	<%= yield %>


	<p class="userinfo">
		<% if current_user %>
		Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
		<% else %>
		<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
		<% end %>
	</p>

	
	<p class="create_product">
	<% if current_user %>
	<a id="current_user"><%= link_to "Create Products", new_product_path %></a>
	<% end %>
	</p>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %> 

<% if @product.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

	<ul>
		<% @product.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<%= link_to "Go to Profile Page.", users_path(@user) %>

<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</div>

<div class="field">
	<%= f.label :url %><br />
	<%= f.text_field :url %>
</div>


<div class="field">
	<%= f.label :price_in_cents %><br />
	<%= f.number_field :price_in_cents %>
</div>


<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/products/_product.html.erb
<div class="photo_name">
	<h4 class="create_products">
		<%= link_to product.name, product_path(product.id) %> 
	</h4>
	<%= link_to image_tag(product.url), product_path(product.id) %>
	<% link_to product_path(product.id) do %>
	<h2>
		<%= product.formatted_price %>
		<%= product.name %>
	</h2>
	<% end %>

	<p><%= truncate(product.description, length: 100) %></p>
</div>

<!-- This variable comes from index.js.erb OR from index.html.erb -->

app/views/products/_productold.html.erb
<div class="photo_name">
	<h4 class="create_products">
		<%= link_to product.id, product_path(product.id) %> 
	</h4>
	<%= link_to image_tag(product.url), product_path(product.id) %>
	<h5>
		<%= product.formatted_price %></br>
		<%= product.name %>
	</h5>
	
	<% link_to product_path(product.id) do %>
	<% end %>

	<p><%= truncate(product.description, length: 100) %></p>
</div>

<!-- This variable comes from index.js.erb OR from index.html.erb -->

app/views/products/_review_form_errors.html.erb
<div id="review-form-errors">
	<% if @review.errors.present? %>
		<% @review.errors.full_messages.each do |error| %>
			<div class="alert">
				<%= error %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/products/_reviews.html.erb
<div id="review-list">
	<% @product.reviews.each do |review| %>

	<div class="review">
		<div class="poster">
			<% if review.user != nil %>
			<em> Posted by <%= review.user.email %></em>
			Added on: <%= review.created_at %>
			<p class="comment">
				<%= review.comment %>
			</p>

			<% if !review.new_record? && current_user.id == review.user_id %>
			<%= link_to "Delete", product_review_path(@product, review), method: :delete, data:{confirm: "Are you sure you want to delete this comment?"}  %>
			<% end %>

			<% if !review.new_record? && current_user.id == review.user_id %>
			<%= link_to "Edit your review", edit_product_review_path(@product,review)%>
			<% end %>

			<% end %>
		</div>

	</div>

	<% end %>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>	
<p>Enter the information to edit the Product<p>

<%= render 'form' %>

<%= link_to "Go to All products", products_path %>

app/views/products/homepage.html.erb
<h1>This is HOMEPAGE</h1>
<%= link_to "Go to All products", products_path %>

app/views/products/index.html.erb
<h1 id="title">ALL PRODUCTS</h1>


<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>


  <%= link_to "Add a product", new_product_path %>
  

<h1>Products <small><%=	page_entries_info @products %></small></h1>

<hr/>

<div id="products">
	<%= render @products %>
</div>

<%= paginate @products %>

app/views/products/index.js.erb
$('#products').append("<%= j(render @products) %>"); //add stuff 
$('.pagination').replaceWith('<%= j paginate(@products) %>');

app/views/products/new.html.erb
<h1>New Product</h1>
<p>Enter the information to create a new product<p>

<%= render 'form' %>
<% link_to 'Back',products_path %>

app/views/products/show.html.erb
<% if current_user %>

<h3 id="review">Reviews</h3>
<p>Reviews for <%= @product.name %></p>


<%= link_to "Go to Profile Page.", user_path %>


<div id="review-list">
	<%= render :partial => "reviews" %>	
</div>


<%= link_to "Edit product", edit_product_path %>

<%= link_to "Delete", product_path(@product), method: :delete, data:{confirm: "Are you sure you want to delete this comment?"}  %>

<p id="photo_at_review">
	<%= image_tag(@product.url) %>
</p>

<!-- ここで写真が出るのは、既にコントローラーで探されているから。
-->

	<%= form_for [@product,@review], :remote => true do |f| %>
	
		<div id="review-form-errors">
			<%= render :partial => "/products/review_form_errors" %>
		</div>

		<% if @review.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@review.errors.count, "errors") %>prohibited this review from being saved:</h2>

			<ul> 
				<% @review.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="field">
			<%= f.label :comment %><br/>
			<%= f.text_area :comment %>
		</div>

		<div class="actions">
			<%= f.submit %> 
		</div>
	<% end %>

	<%= link_to "Go to All products", products_path %>

<% else %>
	<p>plaease <%= link_to "log in", new_session_path %> to add a review. </p>
<% end %>


<script type="text/javascript">
	$(function() {
		$("#new_review")
			.on('ajax:beforeSend',function() {
				$("input[type='submit']")
					.val('saving...')
					.attr('disabled','disabled');
			})
			.on('ajax:complete',function(){
				$("input[type='submit']")
					.val('Create Review')
					.removeAttr('disabled');
			});
	});
</script>

app/views/reviews/create.html.erb
<h1>Your comment was uploaded !!</h1>

<%= link_to "Go to All products", products_path %>

app/views/reviews/create.js.erb
alert("I am responding to your request!");
$("#review-lisst").html("<%= escape_javascript(render(:partial => 'products/reviews')) %>")

<% if @review.errors.present? %>
	$("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
	$("#review-form-errors").html("");
	$("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
	$("#new_review")[0].reset();
<% end %>

app/views/reviews/destroy.html.erb
<h1>Your comment was deleted!</h1>
<%= link_to "All products", products_path %>	

app/views/reviews/edit.html.erb
<h1>Edit your review</h1>	
<p>Enter the information to edit the Product<p>



	
	<%= form_for([@product, @review]) do |f| %> 

	<div class="field">
		<%= f.label :comment %><br/>
		<%= f.text_area :comment %>	
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>


	<% end %>

<!-- nested require [] -->
<!-- Updateが必要 -->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<p>This is index</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

	<% if @user.errors.any? %>
		<div class ="error_messages"> 
			<h2>Form is invalid></h2>
			<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</div>

	<div class="actions"><%= f.submit %></div>

<% end %>

app/views/users/show.html.erb
<p>This is your User page!!</p>
<% if current_user %>
	<p>Welcome <%= current_user.name %>!!!</p>
<% end %>